# Generated by Django 3.1.7 on 2021-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('align', models.CharField(choices=[('l', 'Left'), ('r', 'Right')], max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
    ]
